services:
  db:
    image: postgres:15-alpine
    container_name: optisaas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: optisaas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: optisaas-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db:5432/optisaas?schema=public"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: optisaas-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  n8n:
    image: n8nio/n8n:alpine
    container_name: optisaas-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=motdepasse
      - EXECUTIONS_PROCESS=main
    volumes:
      - ./n8n-data:/home/node/.n8n
    restart: always

volumes:
  pgdata:
